apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: votingApp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: votingApp 
    spec:
      containers:
        - name: votingApp 
          image: raireg1.azurecr.io/votingApp 
          ports:
          - containerPort: 8080